simulation_parameters:
  houses_init: 10 # Initial number of houses in the model
  sim_time: 10 # Simulation time in years
  time_step: 0.1 # Time step for the simulation in years

model_parameters:
  initial_pop: 100 # Initial population in the model
  avg_household_size: 4 # Number of people per household
  private_investment: 100  # Amount of private investment in the model
  base_construction_rate: 0.5 # Base rate of construction in the model it should be 0 to 1
  total_land_area: 1000 # Total land area in the model
  housing_demolition_rate: 0.3 # Rate of housing demolition in the model it should be 0 to 1
  property_tax: 100 # amount of money to be paid as property tax in the model
  avg_land_per_house: 5 # Average land per house in the model
  avg_housing_cost: 200 # Average cost of housing in the model
  # zoning_mult:          2.0     # zoning max density multiplier
  
  
response_function_parameters:
  scarcity_sensitivity: 0.5     # controls how sharply cost rises with scarcity
  slack_sensitivity: 0.3     # controls how sharply cost falls with slack
  K_fin:                0.5     # half‐saturation for financing effect, the higher the value it will saturate faster
  elasticity_tax:       3.0     # tax→construction sensitivity
  k_eng:                5.0     # stakeholder engagement steepness
  mid_eng:              0.5     # stakeholder engagement midpoint
  land_per_house_base:  0.0     # computed as total_land_area/initial_houses
  K_inv:                0.5     # half‐saturation for private investment
  K_serv:              0.5     # half‐saturation for service supply
  pop_growth_rate:      0.05    # population growth rate per year
  pop_carrying_capacity: 5000 # maximum population capacity of the model
  K_pub:               0.5     # half‐saturation for public transportation investment
  K_priv:              0.5     # half‐saturation for private transportation investment

model_policies:
  financial_availability:       0.8   # 0–1 index of credit availability
  tax_rate:                     0.3   # 0–1 fraction (e.g. 20%)
  fraction_of_funding_for_transportation: 0.7 # 0–1 fraction
  zoning_and_regulation:        0.7   # 0–1 index
  fraction_of_investment_in_public_transportation: 0.6 # 0–1 fraction
  engagement_with_stakeholders: 0.5   # 0–1 index

delays:
  tax_effect_delay:          2.0   # time units to “ramp up” tax effect
  private_investment_delay:  1.5   # likewise for private‐investment effect
  housing_stock_delay:        3.0   # likewise for housing stock effect